module VerifyExamples.DictAny.Foldl0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import DictAny exposing (..)
import DictAny as Dict exposing (Dict)

type alias User = { age : Int }

getAges : Dict String User -> List String
getAges users =
    Dict.foldl compare addAge [] users
addAge : String -> User -> List String -> List String
addAge _ user ages =
    user.age :: ages



spec0 : Test.Test
spec0 =
    Test.test "#foldl: \n\n    getAges users\n    --> [33,19,28]" <|
        \() ->
            Expect.equal
                (
                getAges users
                )
                (
                [33,19,28]
                )