module VerifyExamples.DictAny.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import DictAny exposing (..)
import DictAny as Dict exposing (Dict)

type alias Value = Float
type alias Key =
    { id : Int
    , name : String
    }

compareIds : Key -> Key -> Order
compareIds a b =
    compare a.id b.id
data : Dict Key Value
data =
    Dict.fromList compareIds
        [ ( { id = 1, name = "Bert" }, 1.01 )
        , ( { id = 2, name = "Fred" }, 2.02 )
        , ( { id = 42, name = "Douglas" }, 54.0 )
        ]



spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    data |> Dict.get compareIds { id = 1, name = \"Bert\" }\n    --> Just 1.01" <|
        \() ->
            Expect.equal
                (
                data |> Dict.get compareIds { id = 1, name = "Bert" }
                )
                (
                Just 1.01
                )