module VerifyExamples.SetAny.Filter0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import SetAny exposing (..)
import SetAny as Set exposing (Set)



positives : Set Int
positives =
    numbers |> Set.filter compare (\x -> x > 0)
numbers : Set Int
numbers =
    [ -2, -1, 0, 1, 2 ] |> Set.fromList compare



spec0 : Test.Test
spec0 =
    Test.test "#filter: \n\n    positives\n    --> [1,2] |> Set.fromList compare" <|
        \() ->
            Expect.equal
                (
                positives
                )
                (
                [1,2] |> Set.fromList compare
                )