module VerifyExamples.SetAny.ModuleDoc0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import SetAny exposing (..)
import SetAny as Set exposing (Set)

type Item
    = Brush
    | Soap
    | Shampoo
    | Towel

comparer : Item -> Item -> Order
comparer a b = compare (itemToInt a) (itemToInt b)
items : Set Item
items = [ Brush, Soap, Towel ] |> Set.fromList comparer
itemToInt : Item -> Int
itemToInt item =
    case item of
        Brush -> 1
        Soap -> 2
        Shampoo -> 3
        Towel -> 42



spec0 : Test.Test
spec0 =
    Test.test "Module VerifyExamples: \n\n    items |> Set.toList\n    --> [ Brush, Soap, Towel ]" <|
        \() ->
            Expect.equal
                (
                items |> Set.toList
                )
                (
                [ Brush, Soap, Towel ]
                )